# Generated by Django 5.2.6 on 2026-01-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_acount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('internal', 'Internal')], default='bank', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_payments', to='finance_acount.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
