# Generated by Django 5.2.6 on 2025-11-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_tag_category_parent_product_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
