# Generated by Django 5.2.6 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_options_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
